#!/usr/bin/python3
def raise_exception():
    res = list((lambda x: x + 2)(3))
    return (res)
